name: TIOGA CI

on:
  push:
    branches:
      - exawind
  pull_request:
    branches:
      - exawind

concurrency:
  group: ${{github.ref}}-${{github.head_ref}}-ci
  cancel-in-progress: true

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v4
    - name: Check formatting
      uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: './src'
        exclude: '.'
        extensions: 'h,cpp'
        clangFormatVersion: 16
  # build:
  #   runs-on: ${{matrix.os}}
  #   strategy:
  #     matrix:
  #       #os: [ubuntu-latest, macos-latest]
  #       os: [ ubuntu-latest ]
  #       build_type: [Release, Debug]
  #       include:
  #         # - os: macos-latest
  #         #   build_deps: brew install open-mpi && brew link gcc
  #         - os: ubuntu-latest
  #           build_deps: sudo apt-get install mpich libmpich-dev
  #   name: ${{matrix.os}} - ${{matrix.build_type}}
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install dependencies
  #       run: ${{matrix.build_deps}}
  #     - name: Configure and build
  #       run: |
  #         cmake -Bbuild -DCMAKE_Fortran_COMPILER=$(which mpif90) .
  #         cmake --build build -- -j $(nproc)

  # analyze:
  #   name: CodeQL analysis
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Install dependencies
  #       run: sudo apt-get install mpich libmpich-dev

  #     - name: Initialize CodeQL
  #       uses: github/codeql-action/init@v1
  #       with:
  #         languages: cpp

  #     - name: Configure and build
  #       uses: github/codeql-action/autobuild@v1

  #     - name: Analyze
  #       uses: github/codeql-action/analyze@v1
